// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSchMstBranch = "sch_mst_branch"

// SchMstBranch mapped from table <sch_mst_branch>
type SchMstBranch struct {
	BranchID     string  `gorm:"column:branch_id;primaryKey" json:"branch_id"`
	SchoolID     string  `gorm:"column:school_id" json:"school_id"`
	BranchName   string  `gorm:"column:branch_name" json:"branch_name"`
	BranchLat    float64 `gorm:"column:branch_lat" json:"branch_lat"`
	BranchLon    float64 `gorm:"column:branch_lon" json:"branch_lon"`
	BranchRadius float64 `gorm:"column:branch_radius" json:"branch_radius"`
	IsActive     bool    `gorm:"column:is_active" json:"is_active"`
	BranchCode   string  `gorm:"column:branch_code" json:"branch_code"`
	StartTime    string  `gorm:"column:start_time" json:"start_time"`
	EndTime      string  `gorm:"column:end_time" json:"end_time"`
}

// TableName SchMstBranch's table name
func (*SchMstBranch) TableName() string {
	return TableNameSchMstBranch
}
