// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	
)

const TableNameSchMstSchool = "sch_mst_school"

// SchMstSchool mapped from table <sch_mst_school>
type SchMstSchool struct {
	SchoolID      string    `gorm:"column:school_id;primaryKey" json:"school_id"`
	SchoolName    string    `gorm:"column:school_name" json:"school_name"`
	SchoolCity    string    `gorm:"column:school_city" json:"school_city"`
	SchoolAddress string    `gorm:"column:school_address" json:"school_address"`
	// UserID        string    `gorm:"column:user_id" json:"user_id"`
	// IsActive      bool      `gorm:"column:is_active" json:"is_active"`
	// DateJoin      time.Time `gorm:"column:date_join" json:"date_join"`
	// DateExpired   time.Time `gorm:"column:date_expired" json:"date_expired"`
	// SchoolCode    string    `gorm:"column:school_code" json:"school_code"`
	SchoolEmail   string    `gorm:"column:school_email" json:"school_email"`
	//SchoolLogo    string    `gorm:"column:school_logo" json:"school_logo"`
}

// TableName SchMstSchool's table name
func (*SchMstSchool) TableName() string {
	return TableNameSchMstSchool
}
