// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSchTrxStoryChild = "sch_trx_story_child"

// SchTrxStoryChild mapped from table <sch_trx_story_child>
type TransactionStoryChild struct {
	StoryChildID string `gorm:"column:story_child_id;primaryKey" json:"story_child_id"`
	StoryID      string `gorm:"column:story_id" json:"story_id"`
	ChildID      string `gorm:"column:child_id" json:"child_id"`
}

// TableName SchTrxStoryChild's table name
func (*TransactionStoryChild) TableName() string {
	return TableNameSchTrxStoryChild
}
